### ISSUE TITLE
i still can't get it to work

### ISSUE THREAD

**Issue by drakulaboy** [KyuubiRan/EzXHepler-template#1]
please for the love of android help :D , i don't understand how to do it, make please [**this example**](https://github.com/rovo89/XposedBridge/wiki/Development-tutorial#final-steps-execute-your-own-code-beforeafter-the-method-call) in kotlin and [**this**](https://github.com/rovo89/XposedBridge/wiki/Replacing-resources#modifying-layouts) then i will be able to understand the code and do other stuff by my own, please, thank you!

**Comment by KyuubiRan** [comment]
You need choose the xposed-scope "com.android.systemui" and use 
```kotlin
findMethod("com.android.systemui.statusbar.policy.Clock") { name == "updateClock" }.hookAfter { param -> 
    val tv = param.thisObject as TextView
    val text = tv.text
    tv.text = "${text} :)"
    tv.color = Color.RED
}
```
Use this template and modifiy MainHook.kt & Example.kt
Change the [target in MainHook.kt](https://github.com/KyuubiRan/ezxhepler-template/blob/master/app/src/main/java/com/example/template/MainHook.kt#L10) and the [array.xml](https://github.com/KyuubiRan/ezxhepler-template/blob/master/app/src/main/res/values/arrays.xml#L4) &
Change the [hook in Example.kt](https://github.com/KyuubiRan/ezxhepler-template/blob/master/app/src/main/java/com/example/template/hook/ExampleHook.kt#L9) , it has two-way to hook same method, you can use one of them.

Resources replacement is same as that example

**Comment by drakulaboy** [comment]
what now? https://imgur.com/a/KTnUM87

**Comment by drakulaboy** [comment]
what now? https://imgur.com/a/KTnUM87

**Comment by KyuubiRan** [comment]
oh you need typecasting because the type of param.thisObject is an _Object_ (in kotlin it called _Any_)
try 
```kotlin
val tv = param.thisObject as TextView
```

**Comment by drakulaboy** [comment]
finally :D 
now only 
`tv.**color** = Color.RED `
is red
but i replaced it with 
`tv.setTextColor(Color.RED)`
and it worked

**Comment by KyuubiRan** [comment]
:D I misremembered
